- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier

- type: department
  id: Civilian
  name: department-Civilian
  description: department-NFCivilian-description # Frontier
  color: "#9FED58"
  weight: -10
  roles:
   - Bartender # Frontier
   - Botanist # Frontier
   - Boxer # Frontier
   - Chaplain # Frontier
   - Chef # Frontier
   - Clown # Frontier
   - HeadOfPersonnel # Frontier
   - Lawyer # Frontier
   - Librarian # Frontier
   - Mime # Frontier
   - Musician # Frontier
   - Passenger # Frontier
   - Reporter # Frontier
   - Visitor # Frontier
   - Zookeeper # Frontier
   - ServiceWorker # Frontier
   - Contractor # Frontier
   - Mercenary # Frontier
   - Pilot # Frontier
   - Janitor
- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-NFCentralCommand-description # Frontier
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN # Frontier
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad # Frontier
  - ERTMailCarrier # Frontier
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-NFCommand-description # Frontier
  color: "#334E6D"
  roles:
   - ChiefEngineer # Frontier
   - ChiefMedicalOfficer # Frontier
   - HeadOfPersonnel # Frontier
   - HeadOfSecurity # Frontier
   - ResearchDirector # Frontier
   - Quartermaster # Frontier
   - StationTrafficController # Frontier
   - StationCaptain # hardlight
  primary: false
  weight: 100
 # editorHidden: true # Frontier

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant


- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - PrisonGuard
  - Prisoner

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  primary: false
