- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 9000 #2.5 hrs
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-hire # Frontier
  access:
  - Research
  - Maintenance
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff
